# Generated by Django 3.1.1 on 2020-11-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_formulario',
            field=models.DateField(blank=True, null=True),
        ),
    ]
