# Generated by Django 3.1.1 on 2020-11-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_fecha_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mail',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
