# Generated by Django 3.1.1 on 2020-11-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20201105_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
